/*
 Navicat Premium Data Transfer

 Source Server         : gorilla
 Source Server Type    : MySQL
 Source Server Version : 80030
 Source Host           : 192.168.105.201:13306
 Source Schema         : gorilla

 Target Server Type    : MySQL
 Target Server Version : 80030
 File Encoding         : 65001

 Date: 04/10/2022 20:19:14
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for galaxy
-- ----------------------------
DROP TABLE IF EXISTS `galaxy`;
CREATE TABLE `galaxy`  (
  `id` int(0) NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `description` varchar(3000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `link` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `nft_rarity` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `ads_chance` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `arts_link` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `img_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `created_at` timestamp(0) NULL DEFAULT NULL,
  `updated_at` timestamp(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 33 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of galaxy
-- ----------------------------
INSERT INTO `galaxy` VALUES (1, '0000001', 'Ethereum', 'Ethereum is a decentralized open-source blockchain system that features its own cryptocurrency, Ether. ETH works as a platform for numerous other cryptocurrencies, as well as for the execution of decentralized smart contracts.  Ethereum was first described in a 2013 whitepaper by Vitalik Buterin. Buterin, along with other co-founders, secured funding for the project in an online public crowd sale in the summer of 2014. The project team managed to raise $18.3 million in Bitcoin, and Ethereum’s price in the Initial Coin Offering (ICO) was $0.311, with over 60 million Ether sold. Taking Ethereum’s price now, this puts the return on investment (ROI) at an annualized rate of over 270%, essentially almost quadrupling your investment every year since the summer of 2014.  The Ethereum Foundation officially launched the blockchain on July 30, 2015, under the prototype codenamed “Frontier.” Since then, there has been several network updates — “Constantinople” on Feb. 28, 2019, “Istanbul” on Dec. 8, 2019, “Muir Glacier” on Jan. 2, 2020, “Berlin” on April 14, 2021, and most recently on Aug. 5, 2021, the “London” hard fork.  Ethereum’s own purported goal is to become a global platform for decentralized applications, allowing users from all over the world to write and run software that is resistant to censorship, downtime and fraud.', 'https://www.ethereum.org/', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (2, '0000002', 'USD Coin', 'USD Coin (known by its ticker USDC) is a stablecoin that is pegged to the U.S. dollar on a 1:1 basis. Every unit of this cryptocurrency in circulation is backed up by $1 that is held in reserve, in a mix of cash and short-term U.S. Treasury bonds. The Centre consortium, which is behind this asset, says USDC is issued by regulated financial institutions. <br/> The stablecoin originally launched on a limited basis in September 2018. Put simply, USD Coin’s mantra is “digital money for the digital age” — and the stablecoin is designed for a world where cashless transactions are becoming more common. <br/> Several use cases have been unveiled for the USD Coin. As well as providing a safe haven for crypto traders in times of volatility, those behind the stablecoin say it can also allow businesses to accept payments in digital assets, and shake up an array of sectors including decentralized finance and gaming.s', 'https://www.centre.io/usdc', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (3, '0000003', 'IDZ Asset 0', 'For 5 years, we have been working tirelessly to revolutionise the identity/ownership space to finally introduce the ID ecosystem, so you can have ALL THE CONTROL in YOUR hands. <br/> Take control of your data. Own and control your assets, contracts, chats and files. <br/> Asset 0 is the first asset in the ID ecosystem. Its value is linked to the number of users in IDZ. As the number of users in the system increases, so does the value. <br/> Asset 0 comes with a buyback guarantee, meaning you will always find a buyer for it after IDZ’s IPO. <br/> When you own Asset 0, you become an IDZ Ambassador giving you access to exclusive benefits. <br/> In the primary market, the floor price of Asset 0 will increase progressively on a weekly basis. Secure its cheapest price now!', 'https://idz.com/', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (4, '0000004', 'Cybee NFTs with Passive Income', 'Cybee DAO aims to establish the biggest NFT community and a huge Dapp and GameFi ecosystem that provides passive income and benefits for all holders. <br/> Once you mint a Cybee, you will get the Cybee DAO membership and $CBD token rewards. Meanwhile, you can get the ticket to Invite to Earn and earn ETH rewards, receive 3D Cybee and NFT Derivatives airdrop and play to earn $CBD in Cybee Ecosystem. <br/> In addition to the appreciation of NFT, Cybee DAO will distribute a portion of the net revenue to all holders at a fixed time, such as quarterly or annually. The amount will be calculated based on the proportion to their holdings.', 'https://cybeedao.io/official', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (5, '0000005', 'Azuki Demon', '6666 Azuki went through a chemical explosion, living underground on the ETH blockchain. Azuki Demons are bigger, more brutal and stronger. <br/>   Azuki Demon is Created by 3 Azuki Holders. Once you mint an Azuki Demon, you will get the Azuki Demon DAO membership and Airdrop $ZUKI token rewards. Meanwhile, you can get the ticket to receive 3D Azuki Demon and NFT Derivatives airdrop and play to earn $ZUKI in Zuki Ecosystem. <br/> In addition to the appreciation of NFT holders, Azuki Demon DAO will distribute a portion of the net revenue to all holders at a fixed time, such as quarterly. The amount will be calculated based on the proportion to their holdings.', 'https://azukidemon.com/', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (6, '0000006', 'TapeHeads', 'Access to TapeHead Land on Sandbox for exclusive events <br/> Voting rights on the development of the metaverse <br/> Cost-free rental on TapeHeads Land for events <br/> Sandbox avatars for early adopters <br/> Exclusive first dibs on our future NFT collection drops <br/> Exclusive limited edition and rare merchandise <br/> Access to our \'Music in the Metaverse\' podcast', 'https://www.tapeheads.io/', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (7, '0000007', 'Etherscan', 'Etherscan is a blockchain explorer for the Ethereum network. The website allows you to search through transactions, blocks, wallet addresses, smart contracts, and other on-chain data. It\'s one of the most popular Ethereum blockchain explorers and is free to use. Using Etherscan can help you understand exactly how you interact with the blockchain, other wallets, and DApps. This knowledge can also help you stay safe and spot suspicious behavior. To use Etherscan, you\'ll need a wallet address, transaction ID (TXID), contract address, or another identifier to paste into the search field. The information you\'ll see will depend on what you\'re looking at, but most of it will include associated transactions, addresses, timestamps, and amounts. You can also interact directly with smart contracts to make transactions, check gas fees, and search for airdrops through Etherscan.', 'https://etherscan.io', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000007.png', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (8, '0002900', 'Discoverilla', 'The Discoverilla project aims to guarantee advertising space using 3D Galaxy space to all NFT holders. NFT Holders can advertise projects, companies, products, etc. by using Dashboard and change them as needed. Whitelist Members have a higher probability of banner advertisement effect, and as they contribute to the project, they can secure more space in advertisement probability and 3D space. Let\'s turn more attention to the project and increase our advertising spot with more space and more probability.', 'https://discoverilla.com', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (9, '0008779', 'Ace knight', 'server moderator. highly active and motivated', 'Discord ID: Ace knight#8761', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (10, '0008780', 'Silverstone', 'Work hard pray hard🙌🏻 \\n 120+ Network🌐 \\n -Verified Moderator \\n -Collab Manager -Community Manager', 'Discord ID: Silverstone#2692', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (11, '0008785', 'Micheal Daniel', 'Find your right collab project in 10 minutes!', 'Discord ID: Micheal daniel#7652', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (12, '0008786', 'Steve Boby', 'no mood, push me to the NFT worlds', 'Discord ID: steve boby#7679', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (13, '0008784', 'Peri NFT Promoter', 'Promote your project and launch your NFT to the world', 'Discord ID: peri#0110', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (14, '0008782', 'Dominic david', 'Dm for collaboration manager, moderator, game moderator,hyping in the server', 'Discord ID: Dominic David#1573', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (15, '0009806', 'Worldwide Asset eXchange (WAX)', 'WAX is the safest and most convenient way to create, buy, sell, and trade virtual items - to anyone, anywhere in the world. Hundreds of millions of people around the globe already trade digital and physical items. But the problems that plague the digital goods and trading community have stunted its growth far beneath its full potential.WAX has created a full suite of blockchain-based tools that allows anyone to trade digital or even physical items instantly and securely, to anyone, anywhere.Participants of the Worldwide Asset eXchange gain access to a global community of collectors and traders, buyers and sellers, creators and gamers, merchants, dApp creators, and game developers.', 'https://on.wax.io/about-wax/', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (16, '0009801', 'Highlord', 'The world first AR support video play to earn strategy game. Become a lord and build Highlord', 'https://highlord.io', 'Special', '0.02%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (17, '0009808', 'Meta', 'Meta builds technologies that help people connect, find communities, and grow businesses. When Facebook launched in 2004, it changed the way people connect. Apps like Messenger, Instagram and WhatsApp further empowered billions around the world. Now, Meta is moving beyond 2D screens toward immersive experiences like augmented and virtual reality to help build the next evolution in social technology.', 'https://www.metacareers.com/', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (18, '0009800', 'Growth Engine AI', 'Building Natural Language Processing solutions for government and brands. Automatically convert enterprise knowledge into education materials — so you can grow your team without friction.', 'https://growthengineai.com/', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (19, '0009807', 'SEO Locale, LLC', 'SEO Locale was started in 2015 by digital marketing experts who have over 15 years of experience in this industry. As a full service digital marketing agency, SEO Locale offer specialized in local search engine optimization, national search engine optimization, web design, web development, paid search management, social media management, mobile app development, reputation management, content strategy and optimization and email marketing.', 'https://seolocale.com/', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (20, '0009805', 'Drone Cadets', 'Exposing Our Youth to cutting edge Technology', 'https://dronecadets.com/', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (21, '0009804', 'CodeFutures', 'CodeFutures is a consulting company that provides professional services in software, technology, strategy, and operations. CodeFutures partners with clients to provide everlasting value and meaningful change across all industries (medical, gaming, industrial, etc.).', 'https://www.codefutures.com/', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (22, '0009803', 'SPARK Neuro', 'SPARK Neuro is a leading applied neuroscience company that collects and quantifies data to create machine-learning based brain health biomarkers for better clinical care and therapeutic discovery. SPARK’s Drug Development Dashboard provides intelligence on drug behavior at the earliest stages, saving time and money throughout the course of drug development.', 'https://medical.sparkneuro.com/', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (23, '0009802', 'Broadwing', 'Broadwing is a boutique engineering services organization built around a virtual community of high-quality colleagues that share a love for solving difficult customer challenges.We have a strong emphasis on senior experience, so whether you are just starting your career or are already a well-known expert, you will find that we provide an environment that encourages you to learn and grow. We understand that our diversity feeds our inventive customer solutions, therefore we\'re always on the lookout for people with interesting backgrounds and experiences. You\'ll enjoy working with us if you\'ve ever felt like an outcast in a standard business structure. We work hard to play to your strengths, appreciate you, and welcome you into our culture of cooperation, information sharing, and \'having each other\'s back\' Broadwing has been a completely remote corporation since its inception. We mitigate our rapid growth by insisting on our essential values of collaboration, friendship, and fun, even though we are geographically agnostic. Professionally, our engineers gain experience working on large-platform projects and cutting-edge technologies in industries like Fintech, Healthcare, and Crypto, allowing them to quickly develop an attractive resume with a diverse skill set. Broadwing is the place for you if you despise \'babysitting\' production systems, if you feel like you\'re missing out on evolving technology, and if you want to take your experience to the next level.', 'https://www.broadwing.io/', 'Special', '0.02%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (24, '0001853', 'TRON', 'TRON (TRX) is a decentralized blockchain-based operating system developed by the Tron Foundation and launched in 2017. Originally TRX tokens were ERC-20-based tokens deployed on Ethereum, but a year later they were moved to their own network. <br/> Initially, the project was created with the aim of providing full ownership rights to makers of digital content. The main goal is to help content creators (who receive only a small part of the income) and encourage them with more rewards for their work. How: invite content consumers to reward content makers directly (without intermediaries like YouTube, Facebook or Apple). <br/> The TRON software supports smart contracts, various kinds of blockchain systems, and decentralized applications aka dApps. The cryptocurrency platform uses a transaction model similar to Bitcoin (BTC), namely UTXO. Transactions take place in a public ledger, where users can track the history of operations. <br/> Therefore, the platform was built to create a decentralized Internet and serves as a tool for developers to create dApps, acting as an alternative to Ethereum. Anyone can create dApps on the TRON network, offer content, and in return receive digital assets as compensation for their efforts. The ability to create content and share it openly without hesitation regarding transaction fees is an undeniable advantage of TRON.', 'https://tron.network/', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (25, '0002990', 'Cronos', 'Cronos (CRO) is the native cryptocurrency token of Cronos Chain — a decentralized, open-source blockchain developed by the Crypto.com payment, trading and financial services company. <br/> Cronos Chain is one of the products in Crypto.com’s lineup of solutions designed to accelerate the global adoption of cryptocurrencies as a means of increasing personal control over money, safeguarding user data and protecting users’ identities. The CRO blockchain serves primarily as a vehicle that powers the Crypto.com Pay mobile payments app. <br/> In the future, Crypto.com plans to expand the reach of the CRO platform to power its other products as well. <br/> CRO went live in November-December 2018.', 'https://www.crypto.com/en/chain', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (26, '0001376', 'Solana', 'Solana is a highly functional open source project that banks on blockchain technology’s permissionless nature to provide decentralized finance (DeFi) solutions. While the idea and initial work on the project began in 2017, Solana was officially launched in March 2020 by the Solana Foundation with headquarters in Geneva, Switzerland. <br/> To learn more about this project, check out our deep dive of Solana. <br/> The Solana protocol is designed to facilitate decentralized app (DApp) creation. It aims to improve scalability by introducing a proof-of-history (PoH) consensus combined with the underlying proof-of-stake (PoS) consensus of the blockchain. <br/> Because of the innovative hybrid consensus model, Solana enjoys interest from small-time traders and institutional traders alike. A significant focus for the Solana Foundation is to make decentralized finance accessible on a larger scale.', 'https://solana.com/', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (27, '0001054', 'Avalanche', 'Avalanche is the fastest smart contracts platform in the blockchain industry, as measured by time-to-finality. Avalanche is blazingly fast, low cost, and eco-friendly. Any smart contract-enabled application can outperform its competition by deploying on Avalanche. <br/> Avalanche launched on mainnet, September 21, 2020. Since then, the platform has grown to secure over 450+ individual projects, $118M+ of AVAX burned (reducing supply), 1,350+ individual block-producing validators, and over 1.5M+ community members around the globe.', 'https://avax.network/', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (28, '0000794', 'Binance USD', 'Binance USD (BUSD) is a 1:1 USD-backed stable coin issued by Binance (in partnership with Paxos), Approved and regulated by the New York State Department of Financial Services (NYDFS), The BUSD Monthly Audit Report can be viewed from the official website. Launched on 5 Sep 2019, BUSD aims to meld the stability of the dollar with blockchain technology. It is a digital fiat currency, issued as ERC-20 and supports BEP-2.', 'https://www.binance.com/en/busd', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (29, '0000793', 'Tether', 'USDT is a stablecoin (stable-value cryptocurrency) that mirrors the price of the U.S. dollar, issued by a Hong Kong-based company Tether. The token’s peg to the USD is achieved via maintaining a sum of commercial paper, fiduciary deposits, cash, reserve repo notes, and treasury bills in reserves that is equal in USD value to the number of USDT in circulation. <br/> Originally launched in July 2014 as Realcoin, a second-layer cryptocurrency token built on top of Bitcoin’s blockchain through the use of the Omni platform, it was later renamed to USTether, and then, finally, to USDT. In addition to Bitcoin’s, USDT was later updated to work on the Ethereum, EOS, Tron, Algorand, and OMG blockchains. <br/> The stated purpose of USDT is to combine the unrestricted nature of cryptocurrencies — which can be sent between users without a trusted third-party intermediary — with the stable value of the US dollar. <br/> Stablecoins are increasingly used as an inflation hedge in recent times; compared to keeping fiat currency in a savings account averaging 0.06%, users can lend their stablecoins and earn yields ranging from 3% to as high as 20%. However, keep in mind that regulatory, platform risks and more entail.', 'https://tether.to/', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (30, '0000792', 'Binance', 'Binance is a global cryptocurrency exchange that provides a trading platform for over 100 cryptocurrencies. Since the beginning of 2018, Binance has been considered the largest cryptocurrency exchange in the world in terms of trading volume. Binance\'s English Binance name is based on the combination of the words binary and finance.', 'https://www.binance.com/en', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (31, '0001377', 'Cyber ​​Boar', 'Cyber ​​Boar V.1 is a collection of unique 500 NFTs on the Solana blockchain. This collection will be a pass to the WEB3 ecosystem Universe Cyber ​​Boar. Developed tokenomics and P2E game will bring passive income to our holders. Join us and together we will reach the stars!! Also, this collection will be a WL pass for future Cyber ​​Boar V.2 ( Mutant Version )', 'https://www.launchmynft.io/collections/4RVKD2r8yavsE2mbVAcsBTMTzTeu8Vq8k4gs5efCeEfM/HkiEXtXwbbgEtNQoCSpd', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (32, '0008783', 'Marketing Gorilla', 'Build expensive NFT server & community!', 'Discord ID : cryptohighlord#1942', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);
INSERT INTO `galaxy` VALUES (33, '0008781', 'CryptoNinja', 'NFT & Crypro Die Hard', 'CryptoNinja#0918', 'Normal', '0.01%', 'https://storage.googleapis.com/discoverilla-galaxy/image/0000001.jpg', '', NULL, NULL);

-- ----------------------------
-- Table structure for type
-- ----------------------------
DROP TABLE IF EXISTS `type`;
CREATE TABLE `type`  (
  `id` int(0) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of type
-- ----------------------------

SET FOREIGN_KEY_CHECKS = 1;
